### ISSUE TITLE
(Confirmation)Country code spec.

### ISSUE THREAD

**Issue by taka66** [koikijs/sigure#17]
Confirmation about country code.
I'd like to use country code as ISO-3166-1 alpha2 code.
I think this is standard definition, but is you have any concerns, opinions, please let me know.

I'd like to use following library to show country icon.
This library required to use "ISO-3166-1 alpha2 code" in class name.
https://github.com/lipis/flag-icon-css

Ref)
Search Code :  https://www.iso.org/obp/ui/#search
Japanese : https://ja.wikipedia.org/wiki/ISO_3166-1
English : https://en.wikipedia.org/wiki/ISO_3166-1

**Comment by sideroad** [comment]
I'm agree with u to use the definition.

**Comment by taka66** [comment]
@nabuchi > please implement it as above
